info:
  contact: {}
  title: GinChat
  version: "1.0"
paths:
  /contact/addfriend:
    post:
      parameters:
      - description: 用户ID
        in: query
        name: userId
        type: string
      - description: 好友ID
        in: query
        name: targetId
        type: string
      responses:
        "200":
          description: code, massage, data"}
          schema:
            type: string
      summary: 添加好友
      tags:
      - 聊天界面
  /contact/createCommunity:
    post:
      parameters:
      - description: 用户ID
        in: query
        name: ownerId
        type: string
      - description: 群名称
        in: query
        name: name
        type: string
      - description: 群头像
        in: query
        name: icon
        type: string
      - description: 群描述
        in: query
        name: desc
        type: string
      responses:
        "200":
          description: code, massage, data"}
          schema:
            type: string
      summary: 新建群聊
      tags:
      - 群聊界面
  /contact/loadcommunity:
    post:
      parameters:
      - description: 用户ID
        in: query
        name: ownerId
        type: string
      responses:
        "200":
          description: code, massage, data"}
          schema:
            type: string
      summary: 加载群列表
      tags:
      - 群聊界面
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /searchFriends:
    post:
      parameters:
      - description: 用户ID
        in: query
        name: userId
        type: string
      responses:
        "200":
          description: code, massage, data"}
          schema:
            type: string
      summary: 查询好友列表
      tags:
      - 聊天界面
  /toChat:
    get:
      responses: {}
      tags:
      - IM用户界面
  /toRegister:
    get:
      responses: {}
      tags:
      - 用户注册
  /user/createUser:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: repasswd
        type: string
      responses:
        "200":
          description: code", "massage", "data"}
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/deleteUser:
    get:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      responses:
        "200":
          description: code", "massage", "data"}
          schema:
            type: string
      summary: 注销用户
      tags:
      - 用户模块
  /user/findUserByNameAndPwd:
    post:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      responses:
        "200":
          description: code", "massage", "data"}
          schema:
            type: string
      summary: 用户登录校验
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses:
        "200":
          description: code", "massage", "data"}
          schema:
            type: string
      summary: 查看所有用户
      tags:
      - 用户模块
  /user/updateUser:
    post:
      parameters:
      - description: id
        in: formData
        name: id
        type: string
      - description: name
        in: formData
        name: name
        type: string
      - description: password
        in: formData
        name: password
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: code", "massage", "data"}
          schema:
            type: string
      summary: 修改用户信息
      tags:
      - 用户模块
swagger: "2.0"
